/*
 * EX5.c
 *
 *  Created on: Sep 12, 2024
 *      Author: dangq
 */
#include "EX5.h"

void EX5_Init(void) {
    // Kích hoạt xung nhịp cho cổng A
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};


    GPIO_InitStruct.Pin = SEG_0|SEG_1|SEG_2|SEG_3|SEG_4|SEG_5|SEG_6|SEG_7|SEG_8|SEG_9;

    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    // Kích hoạt xung nhịp cho cổng B
    __HAL_RCC_GPIOB_CLK_ENABLE();


        GPIO_InitStruct.Pin = 	SEG_10|SEG_11|SEG_12|SEG_13|
        						LED_RED_1|LED_YELLOW_1|LED_GREEN_1|
								LED_RED_2|LED_YELLOW_2|LED_GREEN_2|
								LED_RED_3|LED_YELLOW_3|LED_GREEN_3|
								LED_RED_4|LED_YELLOW_4|LED_GREEN_4;

        GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
        GPIO_InitStruct.Pull = GPIO_NOPULL;
        GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
        HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

}

void Trafficlight (int counter){
//Đèn 1 Đỏ
	switch(counter){
	case 0: // đỏ 5-3
		HAL_GPIO_WritePin(GPIOB, LED_RED_1, GPIO_PIN_SET);  // Đỏ bật
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_1, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_1, GPIO_PIN_RESET);  // Xanh tắt
		HAL_GPIO_WritePin(GPIOB, LED_RED_2, GPIO_PIN_RESET);  // Đỏ tắt
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_2, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_2, GPIO_PIN_SET);  // Xanh bật
		HAL_GPIO_WritePin(GPIOB, LED_RED_3, GPIO_PIN_SET);  // Đỏ bật
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_3, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_3, GPIO_PIN_RESET);  // Xanh tắt
		HAL_GPIO_WritePin(GPIOB, LED_RED_4, GPIO_PIN_RESET);  // Đỏ tắt
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_4, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_4, GPIO_PIN_SET);  // Xanh bật
		break;

	case 3: //đỏ 2 - 1
		HAL_GPIO_WritePin(GPIOB, LED_RED_1, GPIO_PIN_SET);  // Đỏ bật
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_1, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_1, GPIO_PIN_RESET);  // Xanh tắt
		HAL_GPIO_WritePin(GPIOB, LED_RED_2, GPIO_PIN_RESET);  // Đỏ tắt
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_2, GPIO_PIN_SET);  // Vàng bật
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_2, GPIO_PIN_RESET);  // Xanh tắt
		HAL_GPIO_WritePin(GPIOB, LED_RED_3, GPIO_PIN_SET);  // Đỏ bật
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_3, GPIO_PIN_RESET);  // Vàng tắt
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_3, GPIO_PIN_RESET);  // Xanh tắt
		HAL_GPIO_WritePin(GPIOB, LED_RED_4, GPIO_PIN_RESET);  // Đỏ tắt
		HAL_GPIO_WritePin(GPIOB, LED_YELLOW_4, GPIO_PIN_SET);  // Vàng bật
		HAL_GPIO_WritePin(GPIOB, LED_GREEN_4, GPIO_PIN_RESET);  // Xanh tắt
		break;

	case 5://Đèn 1 xanh 3s
        HAL_GPIO_WritePin(GPIOB, LED_RED_1, GPIO_PIN_RESET);  // Đỏ tắt
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_1, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_1, GPIO_PIN_SET);  // Xanh bật
        HAL_GPIO_WritePin(GPIOB, LED_RED_2, GPIO_PIN_SET);  // Đỏ bật
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_2, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_2, GPIO_PIN_RESET);  // Xanh tắt
        HAL_GPIO_WritePin(GPIOB, LED_RED_3, GPIO_PIN_RESET);  // Đỏ tắt
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_3, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_3, GPIO_PIN_SET);  // Xanh bật
        HAL_GPIO_WritePin(GPIOB, LED_RED_4, GPIO_PIN_SET);  // Đỏ bật
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_4, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_4, GPIO_PIN_RESET);  // Xanh tắt
        break;

	case 8://Đèn 1 vàng 2s
        HAL_GPIO_WritePin(GPIOB, LED_RED_1, GPIO_PIN_RESET);  // Đỏ tắt
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_1, GPIO_PIN_SET);  // Vàng bật
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_1, GPIO_PIN_RESET);  // Xanh tắt
        HAL_GPIO_WritePin(GPIOB, LED_RED_2, GPIO_PIN_SET);  // Đỏ bật
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_2, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_2, GPIO_PIN_RESET);  // Xanh tắt
        HAL_GPIO_WritePin(GPIOB, LED_RED_3, GPIO_PIN_RESET);  // Đỏ tắt
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_3, GPIO_PIN_SET);  // Vàng bật
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_3, GPIO_PIN_RESET);  // Xanh tắt
        HAL_GPIO_WritePin(GPIOB, LED_RED_4, GPIO_PIN_SET);  // Đỏ bật
        HAL_GPIO_WritePin(GPIOB, LED_YELLOW_4, GPIO_PIN_RESET);  // Vàng tắt
        HAL_GPIO_WritePin(GPIOB, LED_GREEN_4, GPIO_PIN_RESET);  // Xanh tắt
        break;

	}
}

void SevenSEGEX5 (int counter){
	switch (counter){
	case 0: //5 3
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 1: //4 2
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 2: //3 1
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
		break;
	case 3: //2 2
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 4: // 1 1
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
		break;
	case 5://3 5
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 6:// 2 4
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 7:// 1 3
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 8:// 2 2
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_RESET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_RESET);
		break;
	case 9:// 1 1
		HAL_GPIO_WritePin(GPIOA, SEG_0, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_3, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_6, GPIO_PIN_SET);

		HAL_GPIO_WritePin(GPIOA, SEG_7, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, SEG_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, SEG_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOB, SEG_10, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_12, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOB, SEG_13, GPIO_PIN_SET);
		break;
	}
}



