/*
 * EX6.c
 *
 *  Created on: Sep 13, 2024
 *      Author: dangq
 */
#include "EX6.h"

void EX6_Init(void) {

    // Kích hoạt xung nhịp cho cổng A
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};


    GPIO_InitStruct.Pin = 	LED_1|LED_2|LED_3|
							LED_4|LED_5|LED_6|
							LED_7|LED_8|LED_9|
							LED_10|LED_11|LED_12;

    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);


}

void EX6 (int counter){
	switch(counter){
	case 1:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 2:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 3:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 4:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 5:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 6:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 7:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 8:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 9:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 10:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 11:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_SET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_RESET);
		break;
	case 12:
		HAL_GPIO_WritePin(GPIOA, LED_1, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_2, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_3, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_4, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_5, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_6, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_7, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_8, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_9, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_10, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_11, GPIO_PIN_RESET);
		HAL_GPIO_WritePin(GPIOA, LED_12, GPIO_PIN_SET);
		break;
	}
}

